{
    'name': 'Fleet Rent',
    'version': '14.0.1.0.0',
    'depends': ['base', 'fleet', 'purchase', 'product', 'sale', 'stock', 'fleet_rental', 'multi_company_hide_any_menu', 'account', 'l10n_ae', 'hr_expense', 'sale_management', 'purchase'],
    'data': [
            'security/fleet_security.xml',
            'security/ir.model.access.csv',
            'data/fleet_prelocation.xml',
            'data/account_account_template_extend.xml',
            'data/additional_product_charges_data.xml',
            'data/fleet_data.xml',
            'data/vehicle_category_types.xml',
            'wizard/update_history_view.xml',
            'wizard/add_parts_work_order_view.xml',
            'wizard/pending_repair_confirm_view.xml',
            'wizard/add_parts_contact_team_trip_view.xml',
            'wizard/continue_pending_repair_view.xml',
            'views/vehicle_category.xml',
            'views/additional_charges_product.xml',
            'views/service_configuration_warn.xml',
            'views/fleet_customer_view.xml',
            'views/rental_product_view.xml',
            'views/vehicle_category_view.xml',
            'views/fleet_maintenance_view.xml',
            'views/rental_quotation_view.xml',
            'views/fleet_purchase_order.xml',
            'views/fleet_vehicle.xml',
            'views/fleet_service_view.xml',
            'views/workflow_sequence.xml',

    ],
    'demo': [
    ],
    'installable': True,
    'application': True,
}