[options]
addons_path = D:\RAC_16_DEVELOPMENT\odoo16rac\addons,D:\RAC_16_DEVELOPMENT\odoo16rac\custom\addons
db_user = rac_development
db_password = 1234
db_port = 5432
pg_path = C:\Program Files\PostgreSQL\14\bin
http_port = 8069

