{
    'name': 'Fleet Analytic Account',
    'version': '14.0.1.0.0',
    'depends': ['base', 'fleet_rent', 'report_xlsx', 'sales_team'],
    'data': [
            'security/fleet_analytic_account_security.xml',
            'security/ir.model.access.csv',
            'data/fleet_rental_sequence.xml',
            'wizard/vehicle_handover.xml',
            'wizard/vehicle_rent_close.xml',
            'wizard/vehicle_replacement_view.xml',
            'wizard/excel_upload_file.xml',
            'reports/fleet_cost_report.xml',
            'reports/fleet_rental_report.xml',
            # 'reports/fleet_vehicle_utilisation_report.xml',
            'wizard/rent_vehicle_return_view.xml',
            # 'views/contract.xml',
            'views/vehicle_fine_and_salik.xml',
            'views/rental_details_view.xml',
            'views/fleet_rental_invoice.xml',
            'views/fleet_report_invoice.xml',
            'views/rental_customer.xml',
            'views/fleet_vehicle_rental.xml',
            'views/fleet_rent_view.xml',
            'views/invoice_schedule_warning_form.xml',
            'views/fleet_salesman.xml',
            'views/fleet_vehicle_extend.xml',
            'views/print_rental_contract.xml',
            'views/print_rental_contract_view.xml',
            'views/hide_add_a_line.xml',
            'views/vehicle_details.xml',
            'reports/maintenance_qtn.xml',
            'reports/maintenance_qtn_report.xml',
    ],
    'assets': {'web.report_assets_common': ['fleet_analytic_accounting/static/src/scss/contract.scss']},
    'demo': [
    ],

    'installable': True,
    'application': True,
}