from . import fleet_customer
from . import rental_product
from . import vehicle_category
from . import rental_pricing
from . import fleet_purchase_order
from . import fleet_vehicle
from . import rental_additional_charges
from . import product_attribute
from . import fleet_service
from . import fleet_maintenance
from . import fleet_rental_quotation
from . import vehicle_model_categories
from . import res_partner_inherit
